services:

  frontend:
    build: .
    container_name: quantumshop-frontend
    ports:
      - "5178:80"
    depends_on:
      - backend

  backend:
    build: ./server
    container_name: quantumshop-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
