name: QuantumShop CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
 contents: read
 id-token: write
 
jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: server
        run: npm ci --omit=dev

      - name: Build frontend
        run: |
          npm ci
          npm run build

      - name: Build backend Docker image
        run: docker build -t quantumshop-backend:latest ./server

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
         aws-region: ap-south-1
      
      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: quantumshop-backend:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: |
          docker tag quantumshop-backend:latest \
            941894778210.dkr.ecr.us-east-1.amazonaws.com/quantumshop-backend:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
            941894778210.dkr.ecr.us-east-1.amazonaws.com/quantumshop-backend:latest
